export const GET_GITHUB_INITIATE = 'GET_GITHUB_INITIATE'
export const GET_GITHUB_SUCCESS = 'GET_GITHUB_SUCCESS'
export const GET_GITHUB_FAIL = 'GET_GITHUB_FAIL'
export const CHAGE_USER_NAME = 'CHAGE_USER_NAME'
